# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5cf1d7ae971a693e8af2335065deabff590a867d8f1e03ee5de16f1eb1b84300e331e4645e3863a3743906487d8a39775a2c39f950fa767e8ed082f056ba853

test:
  secret_key_base: f42ad1615e0b9e3f56883845bfe424f4f80b0a33c59cd8a446b66ae753286044fc1928868f8ce39439b4f9f44b49ae2c262cab190307035946e15b6428aafa1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
